#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2017-06-09
# @Author  : Bob Liao (codechaser1@gmail.com)
# @Link    : https://github.com/coderchaser
# @Version : python3.4


money={
	# 1 : "壹",
	# 2 : "贰",
	# 3 : "叁",
	# 4 : "肆",
	# 5 : "伍",
	# 6 : "陆",
	# 7 : "柒",
	# 8 : "捌",
	# 9 : "玖",
	# 0 : "零"
	"1": u"壹",
	"2": u"贰",
	"3": u"叁",
	"4": u"肆",
	"5": u"伍",
	"6": u"陆",
	"7": u"柒",
	"8": u"捌",
	"9": u"玖",
	"0": u"零"
}
#将输入金额分组
def group(num_str) :
	group_list=[]
	i=len(num_str)
	while i>=4 :
		group_list.append(num_str[i-4:i])
		i-=4
	if i!=0 :
		group_list.append(num_str[:i])
	group_list.reverse()
	return group_list
#原始读函数,数字必须全部转化为字符串
def read_four(num_four) :
	#读四位分组
	gewei=""
	shiwei=""
	baiwei=""
	qianwei=""
	num_len=len(num_four)
	#当传入的数字为0000时num_len会变成1，会发生list越界
	if num_four[-1]!='0' :
		if num_four[-2]!='0' :
			gewei=num_dic[num_four[-1]]
		else :
			gewei=u"零"+money[num_four[-1]]
	if num_four[-2]!='0' :
		if num_four[-3]!='0' :
			shiwei=money[num_four[-2]]+u"拾"
		else :
			shiwei=u"零"+money[num_four[-2]]+u"拾"
	if num_four[-3]!='0' :
		if num_four[-4]!='0' :
			baiwei=money[num_four[-3]]+u"佰"
		else :
			baiwei=u"零"+money[num_four[-3]]+u"佰"
	if num_four[-4]!='0' :
		qianwei=money[num_four[-4]]+u"仟"
	return qianwei+baiwei+shiwei+gewei
def read_three(num_three) :
	#读三位分组
	gewei=""
	shiwei=""
	baiwei=""
	if num_three[-1]!='0' :
		if num_three[-2]!='0' :
			gewei=money[num_three[-1]]
		else :
			gewei=u"零"+money[num_three[-1]]
	if num_three[-2]!='0' :
		if num_three[-3]!='0' :
			shiwei=money[num_three[-2]]+u"拾"
		else :
			shiwei=u"零"+money[num_three[-2]]+u"拾"
	if num_three[-3]!='0' :
		baiwei=money[num_three[-3]]+u"佰"
	return baiwei+shiwei+gewei
def read_two(num_two) :
	#读二位分组
	gewei=""
	shiwei=""
	if num_two[-1]!='0' :
		if num_two[-2]!='0' :
			gewei=money[num_two[-1]]
		else :
			gewei=u"零"+money[num_two[-1]]
	if num_two[-2]!='0' :
		if num_two[-2] =='1' :
			shiwei=u"拾"
		else :
			shiwei=money[num_two[-2]]+u"拾"
	return shiwei+gewei
def read_one(num_one) :
	#读一位分组
	if num_one!='0' :
		return money[num_one]
	else :
		return ""
#建立调用字典关系
call_read={
	1 : read_one,
	2 : read_two,
	3 : read_three,
	4 : read_four
}
def read(num) :
	#将数字int转化为字符串
	num_str=str(abs(num))
	#分组
	group_list=group(num_str)
	read_part=[]
	if num<0 :
		read_part.append(u'负')
	for i in group_list :
		len_part=len(i)
		read_part.append(call_read[len_part](i))
		if group_list.index(i)== 0 and len(group_list)>1 :
			read_part.append(u'万')
	read_part.append(u'圆')
	print("".join(read_part))
# num=int(input('Your Number: '))
# print(num)
read(-999)
